apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue-todo-ingress
  namespace: vuejs
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: vuetodo.104.238.187.234.vultrusercontent.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: vue-todo-service
            port:
              number: 8088
